---
title: "Manual de estadistica"
output: html_notebook
---
**Elaborado por:**
---
* Alexander Nicholls

* Alejandro Tarazona


**Introducción**
---
R Studio es un lenguaje de programación es una serie de reglas que están diseñadas para realizar procesos en una computadora, es un lenguaje para el cálculo estadístico y la generación de gráficos, que ofrece una gran variedad de técnicas estadísticas y gráficas.

A continuación definiremos e ilustraremos el como se pueden usar estas funciones dentro de este software y como se desarrollan.

**Lista de temas a tratar:**
---

1. [Graficas](#graficas)
    + Boxplot
    + Diagrama de barras
    + Historigrama
    + Diagrama de pastel
    + Diagrama de Pareto
    + Diagrama de dispersión
2. Medidas de tendencia central
    + Moda
    + Media
    + Mediana
    + Maximo y minimo
3. Coeficiente de variación
4. Medidas de asimetria y curtosis
    + Curtosis
    + Asimetria
5. Distribuciones
    + Distribución normal
    + Distribución binomial
    + Distribución de Poisson
6. Probabilidad de eventos
7. Intervalos de confianza
    + T-Test
    + Anova
8. Referencias

---

# 1. Tipos de variables: 

### Cuantitativas:
Son variables cuantitativas si los valores que toman son numericos.

* Discretas: Son discretas si sus valores son enteros.
* Continuas: Son continuas si sus valores pueden tomar valores decimales.

### Cualitativas: 
Son cuantitativas si sus valores no son numericos.

* Nominales: Son nominales si sus valores no se pueden ordenar.
* Ordinales: Son ordinales si sus valores se pueden ordenar.

# 1. Graficas


### 1.1 BOXPLOT

#### ¿Qué es boxplot? 

El gráfico de Boxplot es el más utilizado para mostrar un resumen de una cantidad de datos, adicionalmente para comparar la distribución de varios grupos. Los datos cuantitativos son los unicos que se pueden representar con en esta grafica.

Este tipo de diagramas se crean en R mediante la función de **boxplot()**. Cuya sintaxis es 

    boxplot(x, Datos, Muesca, VarTam, Nombres, Main)

* **x:** es un vector o una fórmula.
* **Datos:** es el marco de datos.
* **Muesca:** es un valor lógico. Establecer como VERDADERO para dibujar una muesca.
* **VarTam:** es un valor lógico. Establecer como verdadero para dibujar el ancho del cuadro proporcional al tamaño de la muestra.
* **Nombres:** son las etiquetas de grupo que se imprimirán debajo de cada diagrama de caja.
* **Main:** se usa para dar un título al gráfico.

Ahora realizaremos un ejemplo:

```{r}
input<-mtcars[,c('mpg','cyl')]
boxplot(mpg~cyl, data = mtcars, xlab = "Number of Cylinders", ylab = "Miles Per Gallon", main = "Mileage Data", horizontal = T)
```

### 1.2 Diagrama de Barras


### 1.3 Historigrama

### 1.4 Diagrama de Pastel

### 1.5 Diagrama de Pareto

### 1.6 Diagrama de Dispersión

---

# 2. Medidas de tendencia central

### 2.1 Moda

### 2.2 Media

### 2.3 Mediana

### 2.4 Máximo y minimo

---

# 3. Coeficiente de variación

---

# 4. Medidas de asimetria y curtosis

### 4.1 Curtosis

### 4.2 Asimetria

---

# 5. Distribuciones

### 5.1 Distribución normal

### 5.2 Distribución binomial

### 5.3 Distribución de Poisson

---

# 6. Probabilidad de eventos

---

# 7. Intervalos de confianza

### 7.1 T-Test

### 7.2 Anova

---

# 8. Referencias
